### ISSUE TITLE
Some service fields don't appear in suggestions

### ISSUE THREAD

**Issue by Kampfkarren** [Kampfkarren/roblox-lua-autofills#21]
Not sure what the pattern is, but I know `UserInputService.GamepadEnabled` doesn't show up.

**Comment by JohnnyMorganz** [comment]
From some testing, it seems that no "Property" MemberType is shown in suggestions for any service, however the others are ("Callback", "Event" ,"Function")

**Comment by JohnnyMorganz** [comment]
The issue is due to the fact all properties have a separate "Security" for Read and Write, in the format:
```json
"Security": {
    "Read": "None",
    "Write": "None"
}
```
However, the autocomplete uses the following check:
https://github.com/Kampfkarren/roblox-lua-autofills/blob/878bb40aa900c01fc65e51619fcf81f444259d72/src/services.ts#L98
