### ISSUE TITLE
(Enum) Autofill doesn't activate after non-space whitespace character

### ISSUE THREAD

**Issue by Reselim** [Kampfkarren/roblox-lua-autofills#4]
[Line in question:](https://github.com/Kampfkarren/roblox-lua-autofills/blob/master/src/extension.ts#L73)

```ts
const textSplit = document.lineAt(position.line).text.substr(0, position.character).split(" ")
```

Suggested fix:

```ts
const textSplit = document.lineAt(position.line).text.substr(0, position.character).match(/S+/g)
```

Alternatively, detection could be reworked to match anything with the following regular expression:

```ts
/Enum\.(\w*)\.?(\w*)/g
```

**Comment by Kampfkarren** [comment]
Regex seems like overkill (especially for the analysis needed to be done)--to get it switched over to Regex wouldn't clean up enough of the code to justify it. It's easier to just use [.trim()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim)
